builds:
  - binary: mackerel-plugin-bitcoin-core
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: dekokun
    name: mackerel-plugin-bitcoin-core
