name: CI/CD
on:
  pull_request: {}
  push:
    branches:
    - main
    tags:
    - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: 1.x
    - name: checkout
      uses: actions/checkout@v5
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: test
      run: go test -race -coverprofile coverage.out -covermode atomic ./...
    - name: Send coverage
      uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
      with:
        verbose: true
        files: coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
  test-docker:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
    - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
    - name: Build
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        context: .
        file: Dockerfile
        platforms: |
          linux/amd64
          linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
  release-binary:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test, test-docker]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-push-docker-image:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [test, test-docker]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
    - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
    - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get version from tag
      id: get_version
      run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"
    - name: Build and push release image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        context: .
        file: Dockerfile
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          dekokun/mackerel-container-agent-bitcoin:latest
          dekokun/mackerel-container-agent-bitcoin:${{ steps.get_version.outputs.VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
