name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-push-docker-image:
    needs: [release-binary]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get version from tag
      id: get_version
      run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"
    - name: Build and push release image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          dekokun/mackerel-container-agent-bitcoin:latest
          dekokun/mackerel-container-agent-bitcoin:${{ steps.get_version.outputs.VERSION }}
